version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 15.a'
      - dependency-name: '@types/puppeteer'
        versions:
          - '>= 6.a'
      - dependency-name: 'puppeteer'
        versions:
          - '>= 6.a'
